### ISSUE TITLE
Obs overlays not working in VERDI 2.1.4 20221109 version

### ISSUE THREAD

**Issue by jherwehe** [CEMPD/VERDI#313] opened 2022-12-05 13:43 UTC
**Describe the bug**
The observations overlay feature of VERDI 2.1.4 became broken in the 20221109 version (see screen capture below), but was working in the previous 20221007 version.  This is a repeat of closed Issue #308.

**To Reproduce**
Steps to reproduce the behavior (as tested on the Atmos Linux system):

1. Open the 20221109 version of VERDI 2.1.4.
2. Load model output file /work/MOD3DEV/jherwehe/verdi/test/bkx/cmaq/wr401/task4/2018/cctm/extr/201808/combine_aconc_v53_intel18.0_2018ff_12US1_20180817
3. Load associated observations file /work/MOD3DEV/jherwehe/verdi/test/wtt/obs_data/Release_Obs_Dev/Tools/Obs_Overlay/AQS_Hourly_PAVE_VERDI_overlay_20180817.ncf
4. Create a tile plot of the O3 field.
5. Click on "Plot", then click on "Add Overlay", then click on "Observations", select O3 from the "Observation Details" box, click "Add Variable", and finish by clicking the "OK" button.
6. See error shown in screen capture below.

**Expected behavior**
The obs overlay feature worked fine in the previous 20221007 version of VERDI 2.1.4. The 20221007 version also worked correctly when loading an entire year of observations to use with the same test model output file above, such as when using observations file /work/MOD3DEV/jherwehe/verdi/test/wtt/obs_data/Release_Obs_Dev/Tools/Obs_Overlay/AQS_Hourly_PAVE_VERDI_overlay_2018.ncf

**Screenshots**
![obs_overlay_problem_with_20221109_VERDI](https://user-images.githubusercontent.com/16904596/205645931-ea22e749-1e8b-49ce-95fb-e76b7edbfa1f.png)

**Tested on the Atmos HPC system:**
- OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
- Linux atmos5 3.10.0-1160.80.1.el7.x86_64 \# 1 SMP Sat Oct 8 18:13:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkang2** [comment] 2022-12-05 14:37
@jherwehe Thanks for testing and identifying this problem. I guess that the addition of the aircraft data overlay messed up the overlay code again, the same as last time.

**Comment by yadongxuEPA** [comment] 2022-12-05 17:53
Confirmed this issue with another set of dataset with the model output file: data/model/CCTM46_P16.baseO2a.36k.O3MAX and observational data file: data/obs/AQS_overlay_2002.2hr.2002152.ncf, got the same error message:
![Test_issue_313_overlay_1](https://user-images.githubusercontent.com/73186639/205707616-b8fcb433-f878-476a-b4db-6b5ac43a5521.png)

**Comment by yadongxuEPA** [comment] 2023-02-07 21:22
**Confirmed this issue with two sets of dataset with VERDI_2.1.4_linux64_20230201.tar.gz on Atmos, found that this issue is not resolved in the new builds.**  We still cannot overlay non-aircraft observations with CMAQ outputs.  Strangely, we got two different error messages shown as below. Please check. 
![test_issue_313_obs_overlay_1](https://user-images.githubusercontent.com/73186639/217368416-a9d9eba5-5b25-41f5-9ee5-7eb3216967f8.png)
![test_issue_313_obs_overlay_2](https://user-images.githubusercontent.com/73186639/217368447-16934a6d-8a71-4d94-97e1-600934c0d958.png)

**Comment by dkang2** [comment] 2023-02-28 18:53
Just did a quick test for the 20230224 build, the overlay worked well on Atmos.

**Comment by yadongxuEPA** [comment] 2023-02-28 19:54
**Confirmed this issue with two sets of dataset with VERDI_2.1.4_linux64_20230224.tar.gz on Atmos, found that this issue has resolved in the new builds** (with timestamps matching and observational data points color scale matching all work properly)
![test_issue_313_CCTM46_O3_AQS_overlay](https://user-images.githubusercontent.com/73186639/221962368-a3b1f05d-ad2a-41c7-9b78-de149404c5c5.gif)
![test_issue_313_combine_aconc_O3_AQS_overlay](https://user-images.githubusercontent.com/73186639/221962442-ea77b443-bb7f-401c-8cb5-452069b0f871.gif)

**Comment by yadongxuEPA** [comment] 2023-09-27 18:20
> The overlay function stopped working again with the 20230924 build.
> 
> <img alt="image" width="794" src="https://user-images.githubusercontent.com/15109047/271067146-82428f15-db38-42ee-8bc4-67c9c1bfd327.png">
Hi Daiwen,

Thanks for retesting this issue.  I got the same error messages when tested 20230924 builds on Atmos5.
Yadong

**Comment by yadongxuEPA** [comment] 2023-10-13 17:25
**Confirmed this issue with VERDI_2.1.4_linux64_20231012.tar.gz on Atmos, found that this issue has resolved in the new builds.**  
![issue_313_20231012_1](https://github.com/CEMPD/VERDI/assets/73186639/e597fa2a-502d-459a-8c62-b6968e1f75fc)

**Comment by jherwehe** [comment] 2023-10-13 19:45
This issue is only partially resolved with VERDI_2.1.4_linux64_20231012.tar.gz.  The observations do plot now, but they are not scaled correctly (which can also be seen in Yadong's screenshot above).  Here is an example of the problem for August 17, 2018 at 20UTC:

![incorrectly_scaled_O3_obs_overlays_using_VERDI214_20231012_17aug2018_20UTC](https://github.com/CEMPD/VERDI/assets/16904596/8f57c897-6d71-409b-9eec-06b58813cbfc)


Using the VERDI_2.1.4_linux64_20221206.tar.gz version, the correctly scaled O3 obs overlays for the same time for these data should appear as seen in the screenshot below:

![correctly_scaled_O3_obs_overlays_using_VERDI214_20221206_17aug2018_20UTC](https://github.com/CEMPD/VERDI/assets/16904596/99c67107-2639-456f-9050-19515c7b0eec)

**Comment by yadongxuEPA** [comment] 2023-10-13 21:11
Tony, 
It seems that you pushed more updates to Atmos today into 20231012 builds.  I retested the issue as Jerry mentioned above and  found the same problem.  Please check into it and push the updates to a new date so that we can track what builds we have tested.  Thanks!
Yadong

**Comment by lizadams** [comment] 2024-01-03 22:50
Tested using VERDI_2.1.5_mac_20240103.tar.gz

Obtained the data from the following locations: 
combine_aconc_v53_intel18.0_2018ff_12US1_20180817
https://drive.google.com/file/d/1HhYp49voK4j36ISwFu-cabrjqUqJitnL/view?usp=drive_link

AQS_Hourly_PAVE_VERDI_overlay_2018.ncf
https://drive.google.com/file/d/1Qwb6ay-MwacaY3mSNywu3n35RstO-JKC/view?usp=drive_link

Used the following command line option to create the tile plot, and then used the GUI to add the observation overlay.

./verdi.sh -f $cwd/../combine_aconc_v53_intel18.0_2018ff_12US1_20180817 -s "O3[1]" -legendBins "0, 14, 28, 42, 56, 70, 84, 98, 112" -ts 21 -g tile -f $cwd/../AQS_Hourly_PAVE_VERDI_overlay_2018.ncf -s "O3[2]"

Confirmed that it works.
<img width="1905" alt="Screen Shot 2024-01-03 at 5 43 37 PM" src="https://github.com/CEMPD/VERDI/assets/1183863/1fb6cbbe-a7f8-4144-8f4d-83b744906742">

However, I noticed that the command line isn't using the "Tile Plot default" and is using the Newton RGB (AVS) so the colors look different than Yadong's plot above.  

I changed the Color map to use the Tile Plot default, and this caused the obs overlay to be cleared, so I had to reload it. Once the Tile Plot default color map is used, it matches Yadong's plot.

<img width="1905" alt="Screen Shot 2024-01-03 at 5 48 07 PM" src="https://github.com/CEMPD/VERDI/assets/1183863/a8ab12ac-274f-4cf9-a7ec-5aa3d192e49f">

**Comment by lizadams** [comment] 2024-01-25 21:44
@yadongxuEPA - Is this issue fixed in the new build for 2.1.5? If so, should we add it to the release notes?

**Comment by yadongxuEPA** [comment] 2024-01-25 21:52
> @yadongxuEPA - Is this issue fixed in the new build for 2.1.5? If so, should we add it to the release notes?

No, we don't need to add this issue in the release note even if it is fully resolved. Because it was working properly in VERDI 2.1.4 to start with, then some code changes made for overlaying aircraft data caused the issue.

**Comment by yadongxuEPA** [comment] 2024-01-25 21:54
> > @yadongxuEPA - Is this issue fixed in the new build for 2.1.5? If so, should we add it to the release notes?
> 
> No, we don't need to add this issue in the release note even if it is fully resolved. Because it was working properly in VERDI 2.1.4 to start with, then some code changes made for overlaying aircraft data caused the issue.

Just want to add, the public users should not have VERDI 2.1.4 20221109 builds.

**Comment by lizadams** [comment] 2024-01-25 22:00
tested on a mac using VERDI_2.1.5_mac_20240124.tar.gz 

Using the following config file (changed extension from .cfg to .txt to allow github to upload the file:
[TilePlot_default_0_to_112.txt](https://github.com/CEMPD/VERDI/files/14058064/TilePlot_default_0_to_112.txt)

Used the command

```
./verdi.command -f $cwd/../combine_aconc_v53_intel18.0_2018ff_12US1_20180817 -s "O3[1]" -ts 21 -configFile $cwd/data/configs/TilePlot_default_0_to_112.txt -g tile -f $cwd/../AQS_Hourly_PAVE_VERDI_overlay_2018.ncf -s "O3[2]"
```

Then in the GUI, used Controls>Plot>Add Overlay> Select O3 > Add variable > select OK

The plot appears to match the correct plot provided by @jherwehe

<img width="1316" alt="Screen Shot 2024-01-25 at 4 53 40 PM" src="https://github.com/CEMPD/VERDI/assets/1183863/e1f5dff0-86b2-4120-b988-e0a257274bee">

So, I think this issue is fully solved now.

**Closed** 2024-01-25 22:01 UTC
Labels: Type: Bug, QA: Ready for Testing, QA: Done Testing, Fixed

**Comment by yadongxuEPA** [comment] 2024-01-26 21:50
Retested this issue with VERDI_2.1.5_linux64_20240124.tar.gz on Atmos and confirmed that it has resolved.
