### ISSUE TITLE
animation issues when 2 maps are in VERDI (associated with MPAS change)

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#53] opened 2016-04-04 19:45 UTC
I can't get a screenshot because of the behavior. This is really weird.
**Began new VERDI session.**
I loaded CCTM47\* and variable O3. Created the tile plot. (Plot 1)
Next, I loaded CCTM46\* and variable NO2. Created the tile plot. (Plot 2)
Animated Plot #2. 
Selected tab for Plot 1. Displayed Plot 1 and then changed to Plot 2 although the tab for Plot 2 was still selected.
Played around with the tabs to see that odd behavior kept occurring.
Stopped animation of Plot 2. Time Step did not change but animation continued (animation button did reset though) and tab for Plot 1 showed as selected.
Select tab for Plot 2. Animation button showed playing and time step was advancing. Stopped the animation but animation kept playing without advancing the time step. Tab for Plot 2 stayed active.
Switch to tab for Plot 1 and this time showed Plot 1.
**Closed VERDI session.**

Implemented code change to 3 files, as provided by MPAS team.
**Began new VERDI session for this new version.**
Above behavior changes. However, there are still problems. If Plot 1 is minimized and then maximized and Plot 2 is animated, lots of flashing occurs. Select Plot 1 in maximized window (not animated). The Plot 1 tab is active and Plot 1 displays BUT then Plot 2 briefly displays in the maximized frame, the map in that frame goes blank, and then Plot 1 again displays in the maximized frame, followed by Plot 2, etc. During this time the tab for Plot 1 remains selected and the time step number does not advance. 
Minimize Plot 1 and then only the Plot 1 tab shows at the bottom of the maximized window, the time step starts advancing, and the Plot 2 flashes in the maximized window. (NOTE: I never maximized Plot #2.)
Stopped the animation for Plot 2. The animation stopped but still displayed in the maximized window.
In the tab for Plot 1, I pressed the button to return to previous docked location, and screen looked like this.
![animationdockingissues_04042016_aftermpaschange](https://cloud.githubusercontent.com/assets/10145737/14259917/23210ef4-fa77-11e5-91c8-469cf2237c8f.PNG)

**Comment by lizadams** [comment] 2019-06-24 23:30
I am not able to reproduce this behavior, so I am closing this issue.
Animate plot appears to work for both tile plots.

**Closed by lizadams** 2019-06-24 23:30 UTC
Labels: QA: Ready for Testing
