### ISSUE TITLE
File/Export from tile plot probe throws NullPointerException

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#84] opened 2016-05-23 00:15 UTC
From Tile Plot, Probe, select a rectangular area, File/Save
VERDI throws NullPointerException error.
![npe_save_spreadsheet_probedarea_05222016](https://cloud.githubusercontent.com/assets/10145737/15457585/eefc0116-2059-11e6-9adc-77fd583fcbf7.PNG)

**Comment by systemsgo** [comment] 2016-07-24 02:59
This appears to be working in shapefile_mpas.

**Comment by lizadams** [comment] 2016-07-26 14:39
This works on mac for the shapefile_mpas.  We need to test on windows and linux as well.

**Comment by lizadams** [comment] 2019-06-24 23:26
closing this issue, as I can't reproduce it.

**Closed by lizadams** 2019-06-24 23:26 UTC
Labels: QA: Ready for Testing
