### ISSUE TITLE
Add new file export types

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#159] opened 2017-11-06 19:51 UTC
If we are stuck exporting only raster images (like PNG, GIF, etc.), instead of vector graphics (PS and PDF), then please add the ability to control the size of raster images instead of being limited by the existing display screen resolution.  Raster images with a larger number of pixels look better when reduced for publication.

**Comment by lizadams** [comment] 2018-12-13 22:59
duplicate of issue 182, this issue is resolved, closing

**Closed by lizadams** 2018-12-13 22:59 UTC
Labels: Action: Save File, QA: Ready for Testing, Type: Enhancement
