### ISSUE TITLE
Error in saved plot configuration

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#156] opened 2017-11-06 19:46 UTC
from Russ Bullock

There is still a problem with the way Verdi retrieves saved plot configurations.  The top contour value on the legend is the same value as the second from the top.  But now there is an added bug.  When I try to open Configure > Configure Plot, to correct this erroneous top contour value, it will not open.  I get the error “Exception in thread “AWT-EventQueue-0” java.lang.ClassCastException: java.lang.String cannot be cast to anl.verdi.formula.Formula$Type”

**Comment by systemsgo** [comment] 2018-01-16 00:28
The problem with the incorrect value is fixed now.  I can't reproduce the ClassCastException but that may have been resolved by the other fix.  Please reopen if you still see it.

**Closed by systemsgo** 2018-01-16 00:28 UTC
