### ISSUE TITLE
GIS layer rotated in polar stereographic projection

### ISSUE THREAD

**Issue by cseppan** [CEMPD/VERDI#65] opened 2016-04-17 19:27 UTC
Example using GRIDCRO2D_2006075_polar_stereographic.ncf:

<img width="1548" alt="polar_stereographic" src="https://cloud.githubusercontent.com/assets/7329179/14589469/d2673206-04b0-11e6-9f12-ddb365b75698.png">

**Comment by systemsgo** [comment] 2016-07-24 02:38
I'm closing this as it's a duplicate of #92 , which is fixed in shapefile_mpas

**Closed by systemsgo** 2016-07-24 02:38 UTC
