### ISSUE TITLE
NullPointerException error when select Save Image As from tile plot

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#50] opened 2016-04-01 20:32 UTC
Started new VERDI session. Selected CCTM46... dataset, O3(ppmV)[1] variable, tile plot. Stayed on time step 1, layer 1. 
Placed cursor on tile map (portion with the tiles and the North America geographic boundaries). Rt-click and select Save Image As from popup box. Save dialog box was displayed. Threw NullPointerException error.
![savetileplotaspng_04012016](https://cloud.githubusercontent.com/assets/10145737/14219214/1571f61c-f827-11e5-8313-bf20d559c694.PNG)
Was still allowed to navigate to desired subdirectory, enter a file name, and Save the file. Saved file shown here.
![cctm46ts1l1_saveaspng](https://cloud.githubusercontent.com/assets/10145737/14219258/52cf500e-f827-11e5-99bd-c0d7f33fd98d.png)

**Comment by cseppan** [comment] 2016-04-19 18:15
I haven't been able to replicate this issue, so maybe it's Windows specific. Since you were able to successfully save the file, it seems like it's not a critical issue.

Just for reference, both the File > Export as Image/GIS menu item and the context menu option Save Image As... use the PlotExporter class. So behavior will be identical for both options.

**Comment by joellenb** [comment] 2016-04-19 20:17
Here is how to replicate this issue. NOTE: The behavior is not identical for File/Export as Image/GIS and for rt-click Save Image As... methods of creating an image file to save.

Here I have tried to home in on when this behavior manifests.

Start a new VERDI session. The **first time only** on tile plot. Create the tile plot. Move the cursor onto the plot.** Rt-click**. **Save Image As...** [get NullPointerException here]  the Save dialog box opens to navigate/enter file name. Click the Save button to save the image.

Problem occurs on the tile plot and on the areal interpolation plot.

Problem does NOT occur on the charts of JFreeChart type.

Creating a new tile plot does NOT throw the error if it was previously thrown during that VERDI session.
Start a new VERDI session. Create a tile plot. File/Export as Image/GIS throws the error. Cancel. rt-click Save Image As... throws error (so have error stack twice in console).
Start a new VERDI session. Create a tile plot. Rt-click Save Image As... throws error. Cancel. File/Export as Image/GIS does NOT have the eror (so have error stack once in console).

**Comment by cseppan** [comment] 2016-04-19 20:29
When the Save dialog box opens, what directory are you initially placed in? Does this change the next time you try to save?

**Comment by joellenb** [comment] 2016-04-19 20:47
Initially placed into My Documents directory. If I do the menu method first, whether I save a file into that directory, open a different directory (subdirectory) and save into that, I get the 1st error. Then, when I do the rt-click method on the same map, it throws the error and opens into the directory where I just saved the file from the menu method.
It throws the error even if I cancel out of the save.

**Comment by joellenb** [comment] 2016-05-11 20:58
NOTE: Error still occurs in v1.6alpha on 5/11/2016.

**Comment by lizadams** [comment] 2018-12-13 19:09
[x] QA check to see if I can reproduce this error on the mac for VERDI_2.0_beta
I am able to create a tileplot of the t2m variable and then right click on the plot and select Save As.
I am able to save this as a png image.
I will try this on a windows machine, and if successful, will close this issue.

**Comment by lizadams** [comment] 2019-06-26 19:24
testing using VERDI_2.0_beta_win64_20190623.zip on windows laptop

I am still getting a null pointer exception when trying to create a tile plot of the t2m variable.
See screenshot of the error message.
> add dataset t2m_only.nc
> select t2m variable
> create tileplot
![t2m_tileplot_VERDI_june23_build(1)](https://user-images.githubusercontent.com/1183863/60208461-598b6e80-9826-11e9-9e47-ef3099279c9e.PNG)
![t2m_save_as_png_error_on_windows(1)](https://user-images.githubusercontent.com/1183863/60208462-598b6e80-9826-11e9-82e1-f3b7c9e037a4.PNG)

**Comment by lizadams** [comment] 2019-06-26 19:31
also seeing a start up error message when I double click on run.bat
![startup_error_VERDI](https://user-images.githubusercontent.com/1183863/60208926-81c79d00-9827-11e9-82b2-26c001d8e3a5.PNG)

**Comment by lizadams** [comment] 2019-06-26 19:37
tried again to reproduce this error, and noticed that it occurs after the pop-up window to save the image as a specific size, but this time the error message was different.
![t2m_save_as_png_error_on_windows 2](https://user-images.githubusercontent.com/1183863/60209300-53968d00-9828-11e9-98ff-365fcf28b855.PNG)

**Comment by lizadams** [comment] 2021-12-08 21:18
Tested using the VERDI 2.1 release on Windows (VERDI_2.1_win64_20211206.zip) and was successfully able to use right click on the plot to save the tile plot as an image. Closing this bug.

**Closed by lizadams** 2021-12-08 21:18 UTC
Labels: Type: Bug, windows
