### ISSUE TITLE
.MOV file does not display correctly

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#270] opened 2021-07-13 20:22 UTC
From Michael Geigert:

Issues with the .mov animation that is produced. On the Linux machine it plays back completely black and on the Windows version, the colors are all random (second image).  The .avi option has been disabled, so there is no alternative format

![mov_issue_1](https://user-images.githubusercontent.com/17141102/125519253-6903e109-7b67-4dc7-898e-5ded723c684f.png)
![mov_issue_2](https://user-images.githubusercontent.com/17141102/125519270-b08750d4-7583-4814-9466-e4e3e9ad10d6.png)

**Comment by yadongxuEPA** [comment] 2021-07-19 18:42
Tested with VERDI_2.1_linux64_20210707.tar.gz and VERDI_2.1_win64_20210707.zip, confirmed that the animate plot can only be played within VERDI GUI.  **User will encounter difficulty to play the saved *.mov files** after closing VERDI GUI because *.mov requires Apple QuickTime to be installed on user's computer, while Apple stopped support for Windows in 2016.  Saving the animated plots in *.mp4 format will be a better choice (require VERDI revisions to be made to add MP4 as alternative choice). 
![issue_270_VERDI_testing_2_07072021](https://user-images.githubusercontent.com/73186639/126210645-26267a56-30f8-4e78-8949-663505643a61.jpg)

**Comment by systemsgo** [comment] 2022-01-19 18:09
Movies are exported as mp4 now.

**Comment by yadongxuEPA** [comment] 2022-01-21 18:22
**Retested with VERDI_2.1.3_linux64_20220118.tar.gz, found that the animate plot could not be exported as *.mp4 movie format.  Please check.** An error message popped-up (shown as below) after I checked the box "Make Movie" and clicked "Start" button. 
![issue_270_testing_20220118_1](https://user-images.githubusercontent.com/73186639/150579977-f202e8be-7f94-4e3d-b7e5-e6417b4c4875.png)

**Comment by yadongxuEPA** [comment] 2022-02-14 16:20
**Retested with VERDI_2.1.3_linux64_20220210.tar.gz, found that the animate plot can be exported as .mp4 movie format without any error messages.  This issue has resolved.**
![issue_270_testing_20220210_1](https://user-images.githubusercontent.com/73186639/153903258-e1b8cc8e-a783-4e3f-a201-abd40f15fa0e.png)

**Closed** 2022-02-17 18:16 UTC
Labels: Action: Animate Plot, Fixed

**Comment by lizadams** [comment] 2022-10-13 16:41
Tested with VERDI_2.1.4_mac_20221007.tar.gz
Confirmed that this works to save animated plot as a movie in mp4 format.
./verdi.sh -f $cwd/data/CAMx/camx.example.grd01 -s "NO2[1]" -g tile
<img width="371" alt="Screen Shot 2022-10-13 at 12 40 22 PM" src="https://user-images.githubusercontent.com/1183863/195655557-c1ddb99f-bb64-4b1d-8b99-5b9d499f0dc7.png">
