### ISSUE TITLE
Tabbed panes accidentally closed

### ISSUE THREAD

**Issue by dkang2** [CEMPD/VERDI#285] opened 2021-12-10 16:12 UTC
**Is your feature request related to a problem? Please describe.**
For the three tabbed panes: Datasets, Areas, and Formulas, if one or more windows are accidentally closed by clicking the x at the upright corner, how can these windows be brought back without restarting Verdi?
**Describe the solution you'd like**
Probably to add entries under the Window Menu by clicking on one entry, it can bring the pane back even it was closed.
**Describe alternatives you've considered**

**Additional context**

**Comment by yadongxuEPA** [comment] 2022-07-07 20:31
**Retested with VERDI_2.1.4_linux64_20220706.tar.gz on Atmos, found that this issue has not resolved.**
Some changes were made in the dropdown menu under "Window" in the top menu bar, but it still did not provide a way to bring back the tabbed panes accidentally closed.
Steps to reproduce the behavior:
1) Loaded a dataset and clicked on "Window" dropdown menu, shown as below:
![VERDI_testing_issue_285_1](https://user-images.githubusercontent.com/73186639/177865451-77043298-ac63-4b99-9a20-d4e0b66600da.png)
2) Intentionally closed "Areas" and "Formulas" panes, checked the "Window" dropdown menu again, shown as below:
![VERDI_testing_issue_285_2](https://user-images.githubusercontent.com/73186639/177865670-67b9eeaa-6ea6-43c8-9665-02c31d6c0f00.png)
3) Tried to click in the checkbox before "Areas" to bring back the closed pane. But "Formulas" disappeared from the dropdown menu which user to bring back "Formulas" pane without restarting VERDI.
![VERDI_testing_issue_285_3](https://user-images.githubusercontent.com/73186639/177866029-0087f988-3428-4f46-8765-5dab47e7de1a.png)

**Comment by dkang2** [comment] 2022-07-20 15:00
Just tested the July 20th build on Atmos. It all worked by bringing back the accidentally closed windows.

**Comment by lizadams** [comment] 2022-07-20 17:12
Also tested the July 20th build on linux and it worked.
VERDI_2.1.4_linux64_20220720.tar.gz

VERDI_2.1.4_mac_20220720.tar.gz
Also tested July 20th build on macOS and it worked to bring back the tabs that were closed by rechecking the window option to see it again.

**Closed** 2022-10-14 17:11 UTC
Labels: Fixed

**Comment by yadongxuEPA** [comment] 2023-12-28 16:17
Checked VERDI_2.1.5_linux64_20231222.tar.gz on Atmos and it worked.

**Comment by lizadams** [comment] 2024-01-03 21:35
Testing with VERDI_2.1.5_mac_20240103.tar.gz and finding an error if I close all windows and then try to bring back the formula window.

Started by running this command:

 ./verdi.sh -f "$cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX" -s "NO[1]+NO2[1]" -ts 12 -g tile -s "O3[1]" -g tile

Then removed all of the windows, and tried to bring them all back. When I tried to bring back the formula window it failed.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "saf.core.ui.dock.DockableFrame.setTitle(String)" because "frame" is null
	at saf.core.ui.actions.WindowMenuAction.actionPerformed(WindowMenuAction.java:52)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:411)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:198)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:399)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:367)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:378)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:367)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

The following formula pane should have the formulas for NO[1]+NO2[1] and O3[1], but it appears to be empty.
<img width="1904" alt="Screen Shot 2024-01-03 at 4 32 19 PM" src="https://github.com/CEMPD/VERDI/assets/1183863/566aff9c-2c54-4791-be31-289bfa6f14d9">

**Comment by yadongxuEPA** [comment] 2024-01-30 16:26
**Tested with VERDI_2.1.5_linux64_20240124.tar.gz on Atmos and found the same error as described by Liz for 20240103 builds.  This issue has not resolved.**
